[workspace]
name = "spider_silkome"
description = "Spider Silkome"
version = "0.1.0"
channels = ['conda-forge','bioconda']
platforms = ['linux-64']

[dependencies]
python = "~=3.10.0"
ipython = "*"
jupyterlab = "*"
loguru = "*"
matplotlib = "*"
notebook = "*"
numpy = "*"
pandas = ">=2.3.3,<3"
pytest = "*"
ruff = "*"
scikit-learn = "*"
tqdm = "*"
typer = "*"
pip = "*"
csvtk = ">=0.34.0,<0.35"
biopython = ">=1.85,<2"
pybedtools = ">=0.12.0,<0.13"
isoquant = ">=3.9.0,<4"
natsort = ">=8.4.0,<9"
gffread = ">=0.12.7,<0.13"
diamond = ">=2.1.16,<3"
augustus = ">=3.5.0,<4"
hmmer = ">=3.4,<4"

[pypi-dependencies]
mkdocs = "*"
python-dotenv = "*"
spider_silkome_module = { path = ".", editable = true }

[feature.mmseqs.dependencies]
mmseqs2 = "*"

[feature.agat.dependencies]
agat = "*"

[environments]
mmseqs = ["mmseqs"]
agat = ["agat"]
